---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-gelf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
# Pref something diff than admin
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kube-gelf
  namespace: kube-system
